language: node_js
node_js:
  - 0.12
  - 4.2.0

cache:
  directories:
    - node_modules

before_install:
  - npm install -g gulp
  - npm install

after_failure:
  - cat /home/travis/build/sghribi/loopback-fixtures/npm-debug.log
